### PR TITLE
Dyeable Planes and Custom Name Retention

### PR DESCRIPTION
**Pull request by Cibernet83**
I added Man of Many Planes to my server, and after a while, everyone had made Scarlet Biplanes. This made it hard to distinguish between every player's planes, so I had the idea to make them dyeable!

-The Scarlet Biplane and Economy Plane can now both be dyed like Leather Armor: by combining multiple dyes with them in the Crafting Table. This gives players a lot more flexibility than simply giving them a dye upgrade slot like Airships from the base mod, as it allows them to choose between more colors than the vanilla 16.
-Dyes can be removed from both planes by picking them up, holding them, and right-clicking a Cauldron filled with water. The same way you remove dye from Leather Armor.
-As requested by one of my server members, the planes added by this mod will now retain their custom item name when placed down and broken. Helping players distinguish more easily between their planes, even in item form.

Here are some videos showing examples of the new features:

[Dyeable Planes](https://youtu.be/voEc_oUrW4k)
[Custom Name Retention](https://youtu.be/NvHMdN-ZXPo)

### CODE REVIEW

**Comment by Luke100000** [comment]
Very nice work! Do you mind if I pull some changes to the base mod as well?

**Comment by Cibernet83** [comment]
Not at all, go ahead!

**Comment by Mayesnake** [comment]
yo, do you have a discord? I was curious how you made this work.

**Comment by Cibernet83** [comment]
I do! I go by Cibernet, so feel free to send me a friend request whenever.

**Pull request merged**
